"""Storyboard content for the KRBL Streamlit MP4 demo renderer."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


DEFAULT_OUTPUT_DIR = Path("rendered_demo")
DEFAULT_NARRATION = DEFAULT_OUTPUT_DIR / "krbl_narration.mp3"
DEFAULT_VIDEO = DEFAULT_OUTPUT_DIR / "krbl_streamlit_demo.mp4"

NARRATION_TEXT = """
AIonOS presents the KRBL agentic inventory replenishment engine.
The demo opens with KRBL's supply chain context: a compressed forty five day harvest window, a three hundred twenty four day inventory holding baseline, thirteen CNFs, more than eight hundred fifty dealers, and more than ninety export markets.
We start with the paddy procurement pool, where the agent watches mandi to Dhuri mill supply, projected demand, receipts, and stock position against the reorder point.
The operating telemetry converts the stream into decisions: current inventory, demand, backlog proxy, procurement savings target, order accuracy, and exception SLA.
Next, the live timeline shows the end to end flow of demand, inventory, receipts, and CNF rebalance signals as the demo day advances.
The agent recommendation view turns those signals into the next replenishment trigger, replenish quantity, release window, projected holding period improvement, and service level protection.
Finally, KRBL GenBI answers business questions in natural language, including current stock, reorder point, holding period reduction, dealer service level, and CNF rebalance recommendations.
This rendered demo is generated by first producing the narration MP3 and then recording the Streamlit flow into an MP4 video.
""".strip()


@dataclass(frozen=True)
class StoryboardStep:
    """A single capture step in the Streamlit walkthrough."""

    name: str
    caption: str
    duration: float
    action: str = "none"
    query: str | None = None


STORYBOARD_STEPS = [
    StoryboardStep(
        name="01_scope",
        caption="KRBL replenishment scope and baseline pressures",
        duration=4.0,
    ),
    StoryboardStep(
        name="02_advance_timeline",
        caption="Advance the telemetry stream to show replenishment movement",
        duration=5.0,
        action="advance_timeline",
    ),
    StoryboardStep(
        name="03_live_timeline",
        caption="Live timeline: demand, inventory, receipts, and CNF rebalance",
        duration=5.0,
        action="open_live_timeline",
    ),
    StoryboardStep(
        name="04_agent_recommendation",
        caption="Agent recommendation: trigger, replenish quantity, and release window",
        duration=5.0,
        action="open_agent_recommendation",
    ),
    StoryboardStep(
        name="05_genbi_inventory",
        caption="GenBI answers current inventory and reorder point questions",
        duration=5.0,
        action="ask_genbi",
        query="What is KRBL's current stock and reorder point?",
    ),
    StoryboardStep(
        name="06_genbi_holding",
        caption="GenBI explains the 324-day holding-period reduction target",
        duration=5.0,
        action="ask_genbi",
        query="How does the 324 day holding period improve?",
    ),
]
